# Generated by Django 5.1.7 on 2025-03-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_body_blog_content_remove_blog_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
