# Generated by Django 5.1.7 on 2025-03-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comment_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='img_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
